version: 0.{build}
image:
- Ubuntu2004
- Visual Studio 2022
configuration: Release
platform: x64
build:
  verbosity: minimal
after_build:
- cmd: 7z a pcmenc.zip encoder\x64\Release\pcmenc.exe readme.md
- sh: 7z a pcmenc.zip encoder\pcmenc.exe readme.md
for:
-
  matrix:
    only:
      - image: Ubuntu

  install:
  - sh: sudo apt install libtbb-dev -y
  build_script:
  - make --directory encoder

artifacts:
- path: '*.zip'