version: 0.{build}
image:
- Ubuntu2004
- Visual Studio 2022
configuration: Release
platform: x64
build:
  verbosity: minimal
after_build:
- cmd: 7z a pcmenc.zip encoder\x64\Release\pcmenc.exe README.md
- sh: 7z a pcmenc.zip encoder/pcmenc README.md
for:
-
  matrix:
    only:
      - image: Ubuntu2004

  install:
  - sh: sudo apt install libtbb-dev --assume-yes --quiet
  build_script:
  - make --directory encoder

artifacts:
- path: '*.zip'